---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clients.freeradius.valdron.ca
spec:
  group: freeradius.valdron.ca
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                ipAddress:
                  type: string
                fromSecretRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                    - name
                secret:
                  type: string
              required:
                - ipAddress
              type: object
          type: object
  names:
    singular: client
    plural: clients
    kind: Client