---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.freeradius.valdron.ca
spec:
  group: freeradius.valdron.ca
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                fromSecretRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                    - name
                username:
                  type: string
                password:
                  type: string
              type: object
          type: object
  names:
    singular: user
    plural: users
    kind: User