---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freeradius-operator
spec:
  template:
    spec:
      serviceAccountName: freeradius-operator
      containers:
        - name: freeradius-operator
          image: jvaldron/freeradius-operator
          imagePullPolicy: Always
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace 